import argparse
import sys

from Unification import Unification
from Geometric import Geometric
from ArithmeticSumGray import ArithmeticSumGray
from ArithmeticSumColor import ArithmeticSumColor
from HistogramGray import HistogramGray
from HistogramColor import HistogramColor

def main():
    #unificationModule()
    #geometricModule()
    #grayArithmeticSumModule()
    #colorArithmeticSumModule()
    #grayHistogramModule()
    colorHistogramModule()

def unificationModule():
    unification = Unification('Resources/cat.png', 'Resources/photoman.png', "L")
    unification.geometricGray()
    unification.rasterGray()
    unification = Unification('Resources/coffee.png', 'Resources/phone.png', "RGB")
    unification.geometricColor()
    unification.rasterColor()

def geometricModule():
    geometric = Geometric('Resources/phone.png', "RGB")
    geometric.translate(100, -100)
    geometric.homogeneousScaling(2.0)
    geometric.nonUniformScaling(2.0, 1.0)
    geometric.rotation(45)
    geometric.axisSymmetry(True, True)
    geometric.customSymmetryX(356)
    geometric.customSymmetryY(356)
    point1, point2 = (50, 50), (100, 100)
    geometric.crop(point1, point2)
    point1, point2 = (50, 50), (100, 100)
    geometric.copy(point1, point2)

def grayArithmeticSumModule():
    gray = ArithmeticSumGray('Resources/photoman.png', 'Resources/lena.png', 'L')
    gray.sumWithConst(30)
    gray.sumWithConst(300)
    gray.sumImages()
    gray.multiplyWithConst(0.5)
    gray.multiplyWithConst(1.5)
    gray.multiplyImages()
    gray.blendImages(0.2)
    gray.blendImages(0.5)
    gray.blendImages(0.8)
    gray.powerFirstImage(0.5)
    gray.powerFirstImage(2)
    gray = ArithmeticSumGray('Resources/cat.png', 'Resources/photoman.png', 'L')
    gray.sumWithConst(30)
    gray.sumWithConst(300)
    gray.sumImages()
    gray.multiplyWithConst(0.5)
    gray.multiplyWithConst(1.5)
    gray.multiplyImages()
    gray.powerFirstImage(0.5)
    gray.powerFirstImage(2)
    gray = ArithmeticSumGray('Resources/cat.png', 'Resources/window-mask.png', 'L')
    gray.multiplyImages()
    gray = ArithmeticSumGray('Resources/cat.png', 'Resources/mask.png', 'L')
    gray.multiplyImages()

def colorArithmeticSumModule():
    color = ArithmeticSumColor('Resources/coffee.png', 'Resources/phone.png', 'RGB')
    color.sumWithConst(30)
    color.sumWithConst(200)
    color.sumWithConst(300)
    color.sumImages()
    color.multiplyWithConst(0.5)
    color.multiplyWithConst(1.5)
    color.multiplyImages()
    color.blendImages(0.2)
    color.blendImages(0.5)
    color.blendImages(0.8)
    color.powerFirstImage(0.5)
    color.powerFirstImage(2)
    color = ArithmeticSumColor('Resources/phone.png', 'Resources/sea.png', 'RGB')
    color.sumWithConst(30)
    color.sumWithConst(200)
    color.sumWithConst(300)
    color.sumImages()
    color.multiplyWithConst(0.5)
    color.multiplyWithConst(1.5)
    color.multiplyImages()
    color.powerFirstImage(0.5)
    color.powerFirstImage(2)

def grayHistogramModule():
    gray = HistogramGray('Resources/photoman.png', 'L')
    gray.calculateHistogram()
    gray.moveHistogram(30)
    gray.moveHistogram(-30)
    gray.localThresholding(5)
    gray.localThresholding(15)
    gray.localThresholding(25)
    gray.localThresholding(50)
    gray.globalThresholding(64)
    gray.globalThresholding(128)
    gray = HistogramGray('Resources/lena.png', 'L')
    gray.calculateHistogram()
    gray.moveHistogram(30)
    gray.moveHistogram(-30)
    gray.localThresholding(5)
    gray.localThresholding(15)
    gray.localThresholding(25)
    gray.localThresholding(50)
    gray.globalThresholding(64)
    gray.globalThresholding(128)
    gray = HistogramGray('Resources/photoman-bright.png', 'L')
    gray.calculateHistogram()
    gray.extendHistogram()
    gray = HistogramGray('Resources/cat-bright.png', 'L')
    gray.calculateHistogram()
    gray.extendHistogram()

def colorHistogramModule():
    color = HistogramColor('Resources/coffee.png', 'RGB')
    #color.calculateHistogram()
    #color.moveHistogram((50, 50, 50))
    #color.moveHistogram((-50, -50, -50))
    #color.moveHistogram((50, 0, 0))
    #color.localSingleThresholding()
    #color.localMultiThresholding()
    #color.globalSingleThresholding()
    color.globalMultiThresholding()
    color = HistogramColor('Resources/phone.png', 'RGB')
    #color.calculateHistogram()
    #color.moveHistogram((50, 50, 50))
    #color.moveHistogram((-50, -50, -50))
    #color.moveHistogram((50, 0, 0))
    #color.localSingleThresholding()
    #color.localMultiThresholding()
    #color.globalSingleThresholding()
    color.globalMultiThresholding()
    color = HistogramColor('Resources/coffee-dark.png', 'RGB')
    #color.calculateHistogram()
    #color.extendHistogram()
    color = HistogramColor('Resources/phone-dark.png', 'RGB')
    #color.calculateHistogram()
    #color.extendHistogram()

if __name__ == '__main__':
    main()